### ISSUE TITLE
Requiring PHP 7.2

### ISSUE THREAD

**Issue by sdlins** [yiisoft/arrays#10]
Why should this require PHP ^7.2 when Yii 3 requires ^7.1? If I have only php 7.1 available (as happens in the work environment) I can't use this lib with Yii 3.

I am aware this is a fw independent lib, but certainly it will be used primarily with Yii 3.

**Comment by machour** [comment]
7.1 security support is going to end next December, so we are going to require PHP 7.2+ for Yii 3 globally.

**Comment by sdlins** [comment]
Thank you 👍🏼
