### ISSUE TITLE
ArrayHelper::getObjectVars() description seems to be out of date.

### ISSUE THREAD

**Issue by arogachev** [yiisoft/arrays#107]
> `It is different from {@see get_object_vars()}`

But it uses nothing more that `get_object_vars()` now. Or am I missing something?

**Comment by vjik** [comment]
This method for cases when need get public only member variables of an object from the object itself.
Call `get_object_vars()` will return all (private, protected and public) variables if it is called within the object itself.

**Comment by arogachev** [comment]
OK, thanks for clarifying. Still I found the mentioned part a bit confusing during fluent reading. Can be improved a bit in my opinion.
