### ISSUE TITLE
ArrayHelper::merge for simple arrays

### ISSUE THREAD

**Issue by loveorigami** [yiisoft/arrays#13]
### What steps will reproduce the problem?

```php
$arr1 = ['2019-01-25'];
$arr2 = ['2019-01-25'];
$arr3 = ['2019-01-25'];

$data = ArrayHelper::merge($arr1, $arr2, $arr3);
```

### What is the expected result?

```php
[
     '2019-01-25'
]
```

### What do you get instead?

```php
[
     '2019-01-25',
     '2019-01-25',
     '2019-01-25'
]
```

### Additional info

| Q                | A
| ---------------- | ---
| Version          | dev-master
| PHP version      | 7.3
| Operating system | Win7

**Comment by samdark** [comment]
That looks like a bug since expected behavior is even [described in the phpdoc](https://github.com/yiisoft/arrays/blob/master/src/ArrayHelper.php#L98):

>  For integer-keyed elements, the elements from the latter array will
> be appended to the former array.
