### ISSUE TITLE
array_key_exists is deprecated with objects PHP 7.4 error PhpUnit 9.0.1.

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/arrays#20]
https://wiki.php.net/rfc/deprecations_php_7_4

Change:

https://github.com/yiisoft/arrays/blob/33643bff4dda619e399d7cd67ee2fe2d105659d3/src/ArrayHelper.php#L183

For:

```
if (is_array($array) && isset($array[$key])) {
    return $array[$key];
}
```

https://github.com/yiisoft/arrays/blob/33643bff4dda619e399d7cd67ee2fe2d105659d3/src/ArrayHelper.php#L189

For:

```
if (strpos($key, '.') !== false) {
    foreach (explode('.', $key) as $part) {
        if (!isset($array[$part])) {
            return $default;
        }
        $array = $array[$part];
    }
    return $array;
}
```

**Comment by xepozz** [comment]
But it applies only to objects

**Comment by terabytesoftw** [comment]
> But it applies only to objects

It is correct but there are packages that use `ArrayHelper::getValue()` on objects and arrays.

**Comment by xepozz** [comment]
The first example checks that `$array` should be an array.
The second example not checks, but we cannot get property as index (I'm about https://github.com/yiisoft/arrays/blob/33643bff4dda619e399d7cd67ee2fe2d105659d3/src/ArrayHelper.php#L192), so we just need to add one more condition before `if (strpos($key, '.') !== false) {` that `$array` is array

**Comment by terabytesoftw** [comment]
Yes, it can also be, but if you read the PHPDOC of the function, it accepts both types array and object.

**Comment by xepozz** [comment]
Object is been processing only on 197 line :)

**Comment by terabytesoftw** [comment]
I will close my PR want to fix it?

**Comment by xepozz** [comment]
You can do it if you want ;)

**Comment by terabytesoftw** [comment]
> Puedes hacerlo si quieres;)

Please fix it I am with active-record
