### ISSUE TITLE
In some cases don't work ReverseBlockMerge modificator in merge method

### ISSUE THREAD

**Issue by vjik** [yiisoft/arrays#41]
### What steps will reproduce the problem?

```php
$a = ['A', 'B'];
$b = ['C', 'D', ReverseBlockMerge::class => new ReverseBlockMerge()];
$c = ['X'];
$result = ArrayHelper::merge($a, $b, $c);
```

### What is the expected result?

`['C', 'D', 'A', 'B', 'X']`

### What do you get instead?

`['A', 'B', 'C', 'D', 'X']`

**Comment by samdark** [comment]
This is because `ReverseBlockMerge` modifier is read from the last array only. Need to decide if this is OK or not...
