### ISSUE TITLE
remove the unexpeced get/set effects

### ISSUE THREAD

**Issue by alexgivi** [yiisoft/arrays#48]
### intro
there is some odd effect. let's see the example:

```php
$value = ArrayHelper::getValue(
 ['a' => ['b' => ['c' => 'value']]],
'a.b.c'
);

 // $value === 'value'

$newArray = ['a' => ['b' => ['c' => 'old']]];

ArrayHelper::setValue($newArray, 'a.b.c', 'new');
// $newArray === ['a' => ['b' => ['c' => 'old']], 'a.b.c' => 'new'];
```

another variant of implementation:

```php
$value = ArrayHelper::getValue(
 ['a.b.c' => value'],
'a.b.c'
);

 // $value === 'value'

$newArray = ['a.b.c' => 'old'];

ArrayHelper::setValue($newArray, 'a.b.c', 'new');
// $newArray === ['a.b.c' => 'old', 'a' => ['b' => ['c' => 'new']]];
```

as we can see - the fact result differs from expected. that's bad.

### the suggestion
it would be good to drop the explode key by dots.
Instead of it, the composite key shoud be passed as array only:

```php
$value = ArrayHelper::getValue(['a' => ['b' => ['c' => 'value']]], 'a.b.c' );
// $value === null;

$value = ArrayHelper::getValue(['a' => ['b' => ['c' => 'value']]], ['a', 'b', 'c'] );
// $value = 'value';

$value = ArrayHelper::getValue(['a' => ['b' => ['c' => 'value']]], explode('.', 'a.b.c'));
// $value = 'value';

$array = ['a' => ['b' => ['c' => 'value']]];
ArrayHelper::setValue($array, 'a.b.c', 'new' );
// $array ===  ['a' => ['b' => ['c' => 'value']], 'a.b.c' => 'new'];

$array = ['a' => ['b' => ['c' => 'value']]];
ArrayHelper::setValue($array, ['a', 'b', 'c'], 'new' );
// $array ===  ['a' => ['b' => ['c' => 'new']]];

$array = ['a' => ['b' => ['c' => 'value']]];
ArrayHelper::setValue($array, explode('.', 'a.b.c'), 'new');
// $array ===  ['a' => ['b' => ['c' => 'new']]];
```

so, the behavior is fixed and predictable, no strange effects.
in case of using objects, dots in keys are bad, but anyway, it's possible to use any keys such as '!s,o$m#e 1key',
and there is no big difference.

| Q                | A
| ---------------- | ---
| Version          | dev
| PHP version      |  any
| Operating system | any

**Comment by vjik** [comment]
Suggestion:

```php
/**
 * @param array|object $array
 * @param string|array $key
 * @param mixed $default
 * @return mixed
 */
public static function getValue($array, $key, $default = null)
{
	...
}

/**
 * @param array|object $array
 * @param string $path
 * @param mixed $default
 * @return mixed
 */
public static function getValueByPath($array, string $path, $default = null) {
	return static::getValue($array, explode('.', $path), $default);
}

/**
 * @param array $array
 * @param string|array|null $key
 * @param mixed $value
 */
public static function setValue(array &$array, $key, $value): void
{
	...
}

/**
 * @param array $array
 * @param string|array|null $path
 * @param mixed $value
 */
public static function setValueByPath(array &$array, string $path, $value): void
{
	static::setValue($array, explode('.', $path), $value);
}
```

This is break BC. In another packages that use dots-way need replace `getValue()` and `setValue()` to `getValueByPath()` and `setValueByPath()`.

**Comment by samdark** [comment]
Last suggestion is fine. Let's have it that way.

**Comment by terabytesoftw** [comment]
> Last suggestion is fine. Let's have it that way.

I think it won't work like that.

**Comment by samdark** [comment]
By `object` @terabytesoftw means `\Closure`.

**Comment by vjik** [comment]
> By `object` @terabytesoftw means `\Closure`. That would, obviously, break so something like the following is needed:

How path can be `\Closure` ?
Now `ArrayHelper::setValue()` also not support `\Closure` for `$path`

**Comment by samdark** [comment]
@vjik I've meant `getValueByPath()`, of course.

**Comment by vjik** [comment]
```php
/**
 * @param array|object $array
 * @param string|\Closure|array $key
 * @param mixed $default
 * @return mixed
 */
public static function getValue($array, $key, $default = null)
{
	...
}

/**
 * @param array|object $array
 * @param string|\Closure|array $path
 * @param mixed $default
 * @return mixed
 */
public static function getValueByPath($array, $path, $default = null) {
	if (is_string($path)) {
		$path = explode('.', $path);
	}
	return static::getValue($array, $path, $default);
}
```

 @terabytesoftw Is this a good solution?

**Comment by terabytesoftw** [comment]
I ask you the getValue() method, is it going to take any changes?

**Comment by vjik** [comment]
> I ask you the getValue() method, is it going to take any changes aditional?

getValue will not support dots. For support dots use getValueByPath.

**Comment by terabytesoftw** [comment]
Well, as I say, it is a matter of testing AR, and Db are more than 2500 tests with multiple conditions, the ideal is to do the PR and see if it breaks, then simply look for the best solution.

**Comment by vjik** [comment]
@terabytesoftw try test PR #50 with AR.
Need replace `getValue()` to `getValueByPath()` for support dots in path.

**Comment by Nex-Otaku** [comment]
Nobody checked issue?

I made two tests, for two parts of issue. First test passes without any errors on existing code. No need to change anything.

Second test fails due to inconsistent code in getValue and setValue.

I solved this inconsistency, by adding 4 lines of code to setValue make it symmetrical with getValue.
