### ISSUE TITLE
Problem with support float as keys

### ISSUE THREAD

**Issue by vjik** [yiisoft/arrays#58]
Functions `getValue`, `getValueByPath`, `setValue`, `setValueByPath`, `remove` support key as float and cast float to string.

Function `index` replace in float values `,` to `.`.

This will work differently depending on PHP settings:

- [precision](https://www.php.net/manual/ru/ini.core.php#ini.precision)
- [decimal_point](https://www.php.net/manual/en/function.localeconv.php) in locale

It can potentially cause problems in some cases with non-standard PHP settings.

Maybe remove support float keys in  `getValue`, `getValueByPath`, `setValue`, `setValueByPath`, `remove` and remove replace  `,` to `,` for float values in `index` ?

**Comment by samdark** [comment]
It can be solved with https://github.com/yiisoft/strings/blob/master/src/NumericHelper.php#L48

**Comment by vjik** [comment]
Ok, I integrate it in arrays.
