### ISSUE TITLE
ArrayHelper::multisort: remove support use \Closure with return multiple keys

### ISSUE THREAD

**Issue by vjik** [yiisoft/arrays#60]
Use `\Closure` which returning the values for comparison purposes is fine.

But use `\Closure` which returning array of keys for sorting ([test](https://github.com/yiisoft/arrays/blob/3fad714d9f8325fe9eb1bfac48d3fee70e68b860/tests/ArraySorterTest.php#L63-L68)) is too much.

If keys for sorting dependencied by array, then user should get this keys before run multisort.

----

```php
$array = [
	['name' => 'a', 'age' => 3],
	['name' => 'b', 'age' => 2],
	['name' => 'B', 'age' => 4],
	['name' => 'A', 'age' => 1],
];
ArraySorter::multisort($array, fn ($item) => ['age', 'name'], SORT_DESC);
```

Now this code is working. Anonymous function for get columns for sort executed for ALL items of array, then used result only first run.

I suggest remove this opportunity. Anonymous function should use only for returning the values for comparison purpose.

**Comment by samdark** [comment]
There's such ability in `getValue()`, `getColumn()`, `index()`, `map()`, `toArray()`. Removing it from one of the methods would make it inconsistent.

**Comment by vjik** [comment]
`getValue()` — `Closure` return value
`getColumn()` — `Closure` return value for each element of array (returned value can be different for each element)
`index()` — `Closure` return key for each element of array (returned key can be different for each element)
`map()` — `Closure` work similarly as in `index()` and `getColumn()`
`toArray()` — `Closure` work similarly as in `getValue()`
`multisort()` — `Closure` return value which use for sorting OR return keys.

Inconsistent: in `multisort()` we can return keys for sorting, but in `getValue()` we don't can return key for get value.

I suggest make so:

`multisort()` — `Closure` return value which use for sorting ~~OR return keys~~.
