### ISSUE TITLE
Change namespace to Yii\Arrays

### ISSUE THREAD

**Issue by samdark** [yiisoft/arrays#7]
I think we need to change namespace to Yii\Arrays. That would allow us adding more classes to the package that won't be helpers.

**Comment by machour** [comment]
- Would the repository/composer library be renamed to yiisoft/arrays too or not?
- How would ArrayHelper be named/namespaced?

**Comment by hiqsol** [comment]
As for me:

- yes: `yiisoft/arrays`
- `Yii\Arrays\ArrayHelper`

**Comment by machour** [comment]
@samdark can we move forward on this so I can resume the migration?

**Comment by samdark** [comment]
Renamed repository.

**Comment by samdark** [comment]
Namespace should be `Yiisoft\Arrays`

**Comment by machour** [comment]
Done. Package should be republished to packagist using the new name.

**Comment by samdark** [comment]
Done.
