### ISSUE TITLE
call getter for property if getter exists.

### ISSUE THREAD

**Issue by wispoz** [yiisoft/arrays#90]
### What steps will reproduce the problem?
```php
class Person {
    private $test = 'asefasef';
    
    public function getTest() 
    {
        return 123123;
    }
    
}
$testValue = \Yiisoft\Arrays\ArrayHelper::getValue($person, 'test');
```
### What is the expected result?
use getter method, output:
123123

### What do you get instead?

```
Fatal error: Uncaught Error: Cannot access private property Person::$test in /usr/src/myapp/vendor/yiisoft/arrays/src/ArrayHelper.php:250
Stack trace:

```
### Additional info
If u use Symfony\Component\PropertyAccess\PropertyAccess you will get output: 
123123

and maybe add some configuring options like in PropertyAccess:

```php
$propertyAccessorBuilder->enableMagicCall(); // enables magic __call
$propertyAccessorBuilder->enableMagicGet(); // enables magic __get
$propertyAccessorBuilder->enableMagicSet(); // enables magic __set
$propertyAccessorBuilder->enableMagicMethods(); // enables magic __get, __set and __call

$propertyAccessorBuilder->disableMagicCall(); // disables magic __call
$propertyAccessorBuilder->disableMagicGet(); // disables magic __get
$propertyAccessorBuilder->disableMagicSet(); // disables magic __set
$propertyAccessorBuilder->disableMagicMethods(); // disables magic __get, __set and __call
```

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      |  7.4
| Operating system |

**Comment by samdark** [comment]
One use case is objects validation via specifying path to the property i.e. `owner.name` to try calling `$object->getOwner()->getName()`.

**Comment by viktorprogger** [comment]
It's kind of black magic. Yii 3 avoids it.
IMHO `ArrayHelper` **must not** deal with object methods. It's not just an ability for user to shoot off his leg, it's a provocation.
In case of validation it's ok either to implement `DataSet` in the validatable object directly, or create a wrapper with this interface. But it is not ok to magically call object methods without a guarantee these methods don't change state or call some services like these:
```php
class Test {
    private $prop = 1;

    public function getProp()
    {
        return $this->prop++;
    }
}
```

```php
class Test2 {
    private $prop = null;

    public function getProp()
    {
        if ($this->prop === null) {
            $infrastructure = $this->httpService->deployInfrastructureFor($this);
            $this->prop = $this->infraRepository->save($infrastructure);
        }

        return $this->prop;
    }
}
```

**Comment by wispoz** [comment]
> It's kind of black magic. Yii 3 usually avoids it.
> IMHO `ArrayHelper` **must not** deal with object methods. It's not just an ability for user to shoot off his leg, it's a provocation.
> In case of validation it's ok either to implement `DataSet` in the validatable object directly, or create a wrapper with this interface. But it is not ok to magically call object methods without a guarantee these methods don't change state or call some services like these:
> ```php
> class Test {
>     private $prop = 1;
> 
>     public function getProp()
>     {
>         return $this->prop++;
>     }
> }
> ```
> 
> ```php
> class Test2 {
>     private $prop = null;
> 
>     public function getProp()
>     {
>         if ($this->prop === null) {
>             $infrastructure = $this->httpService->deployInfrastructureFor($this);
>             $this->prop = $this->infraRepository->save($infrastructure);
>         }
> 
>         return $this->prop;
>     }
> }
> ```

1. Yes i agree with you, and i suggest remove from ArrayHelper ability to deal with objects and make separated package for this.
2. Remove methods html* from ArrayHelper, because this methods dont deal with arrays. Maybe make HtmlHelper

**Comment by viktorprogger** [comment]
I'm agree with you about `html*` methods, it's more about `yiisoft/strings`. But let's keep one issue for 1 theme :)

**Comment by wispoz** [comment]
> I'm agree with you about `html*` methods, it's more about `yiisoft/strings`. But let's keep one issue for 1 theme :)

Yes, you right!
